[build]
buildCommand = "npm install --prefix backend && npm run build --prefix backend"

[deploy]
startCommand = "sh -c 'cd backend && npx prisma migrate deploy && npx prisma db seed && node dist/server.js'"
